coverage:
  status:
    project:
      default: false # disable the default project status
      primitives:
        flags:
          - primitives
        paths:
          - packages/primitives/
      forms:
        flags:
          - forms
        paths:
          - packages/forms/
      charts:
        flags:
          - charts
        paths:
          - packages/charts/

flags:
  primitives:
    paths:
      - packages/primitives/
  forms:
    paths:
      - packages/forms/
  charts:
    paths:
      - packages/charts/
