export const CURSOR_TYPES = [
  "arrow",
  "pointer",
  "text",
  "not-allowed",
  "help",
  "wait",
  "context-menu",
  "none",
  "copy",
  "move",
  "progress",
  "cell",
  "crosshair",
  "vertical-text",
  "alias",
  "zoom-in",
  "zoom-out",
  "no-drop",
  "grab",
  "grabbing",
  "all-scroll",
  "col-resize",
  "row-resize",
  "n-resize",
  "s-resize",
  "e-resize",
  "w-resize",
  "ne-resize",
  "nw-resize",
  "se-resize",
  "sw-resize",
  "nesw-resize",
  "nwse-resize",
] as const;

export type CursorType = (typeof CURSOR_TYPES)[number];
