/**
 * Regenerates `lib/layout/Grid/gridClasses.ts`.
 *
 * Canopy ships no utility CSS — consuming apps generate their utilities by
 * `@source`-scanning `dist/index.js`. Every Tailwind class must therefore exist
 * as a complete literal string in the source; an interpolated name such as
 * `` `${bp}:grid-cols-${n}` `` compiles and tests fine, then produces no CSS at
 * all in a consuming app. Hence these exhaustive lookup tables.
 *
 * Run after changing any grid token array in `lib/types/layout.ts`:
 *
 *   node scripts/generateGridClasses.mjs
 *
 * `tests/layout/gridClasses.test.ts` fails if the committed output drifts.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const OUT = "lib/layout/Grid/gridClasses.ts";

// The token arrays live in TypeScript behind a path alias, so bundle them first.
const tmp = mkdtempSync(join(tmpdir(), "canopy-grid-"));
const entry = join(tmp, "entry.ts");
const bundle = join(tmp, "tokens.mjs");

writeFileSync(
  entry,
  `export { BREAKPOINTS } from "@/types/breakpoints";
export * from "@/types/layout";`,
);
execFileSync("./node_modules/.bin/esbuild", [
  entry,
  "--bundle",
  "--format=esm",
  "--alias:@=./lib",
  `--outfile=${bundle}`,
  "--log-level=warning",
]);

const tokens = await import(bundle);
rmSync(tmp, { recursive: true, force: true });

const { BREAKPOINTS } = tokens;

/** Each table: the prop's token array, the Tailwind utility prefix, the type it satisfies. */
const TABLES = [
  ["GRID_COLS_CLASSES", "GRID_COLS", "grid-cols", "GridCols"],
  ["GRID_ROWS_CLASSES", "GRID_ROWS", "grid-rows", "GridRows"],
  ["GRID_FLOW_CLASSES", "GRID_FLOWS", "grid-flow", "GridFlow"],
  ["GAP_CLASSES", "GAPS", "gap", "Gap"],
  ["GAP_X_CLASSES", "GAPS", "gap-x", "Gap"],
  ["GAP_Y_CLASSES", "GAPS", "gap-y", "Gap"],
  ["GRID_ALIGN_CLASSES", "GRID_ALIGNS", "items", "GridAlign"],
  ["GRID_JUSTIFY_CLASSES", "GRID_JUSTIFIES", "justify", "GridJustify"],
  ["GRID_ALIGN_CONTENT_CLASSES", "GRID_ALIGN_CONTENTS", "content", "GridAlignContent"],
  ["GRID_JUSTIFY_ITEMS_CLASSES", "GRID_JUSTIFY_ITEMS", "justify-items", "GridJustifyItems"],
  ["COL_SPAN_CLASSES", "GRID_SPANS", "col-span", "GridSpan"],
  ["ROW_SPAN_CLASSES", "GRID_SPANS", "row-span", "GridSpan"],
  ["COL_START_CLASSES", "GRID_LINES", "col-start", "GridLine"],
  ["ROW_START_CLASSES", "GRID_LINES", "row-start", "GridLine"],
];

const key = (token) => (/^[a-z][a-zA-Z0-9]*$/.test(token) ? token : JSON.stringify(token));

const table = ([name, tokenArray, utility, type]) => {
  const values = tokens[tokenArray];
  const breakpoints = BREAKPOINTS.map((bp) => {
    const prefix = bp === "base" ? "" : `${bp}:`;
    const entries = values.map((v) => `    ${key(v)}: "${prefix}${utility}-${v}",`).join("\n");
    return `  ${key(bp)}: {\n${entries}\n  },`;
  }).join("\n");
  return `export const ${name} = {\n${breakpoints}\n} satisfies ResponsiveClassMap<${type}>;`;
};

const types = [...new Set(TABLES.map(([, , , t]) => t))].sort();

const contents = `// AUTOGENERATED by scripts/generateGridClasses.mjs — do not edit by hand.
//
// Every class is written out in full because consuming apps generate their
// utilities by scanning Canopy's built output for literal class names.
// Run \`node scripts/generateGridClasses.mjs\` after changing a token array.

import type { ${types.join(", ")} } from "@/types";
import type { ResponsiveClassMap } from "@/utils";

${TABLES.map(table).join("\n\n")}
`;

writeFileSync(OUT, contents);

// Formatting here keeps regeneration idempotent: without it the committed file
// (which `biome check --write` has reformatted) would differ from fresh output.
execFileSync("./node_modules/.bin/biome", ["format", "--write", OUT], { stdio: "inherit" });

const count = TABLES.reduce((n, [, a]) => n + tokens[a].length * BREAKPOINTS.length, 0);
console.log(`Wrote ${OUT}: ${TABLES.length} tables, ${count} classes.`);
