/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SidebarRouteImport } from './routes/sidebar'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as FontsRouteImport } from './routes/fonts'
import { Route as IndexRouteImport } from './routes/index'

const SidebarRoute = SidebarRouteImport.update({
  id: '/sidebar',
  path: '/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const FontsRoute = FontsRouteImport.update({
  id: '/fonts',
  path: '/fonts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fonts': typeof FontsRoute
  '/layout': typeof LayoutRoute
  '/sidebar': typeof SidebarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fonts': typeof FontsRoute
  '/layout': typeof LayoutRoute
  '/sidebar': typeof SidebarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fonts': typeof FontsRoute
  '/layout': typeof LayoutRoute
  '/sidebar': typeof SidebarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fonts' | '/layout' | '/sidebar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fonts' | '/layout' | '/sidebar'
  id: '__root__' | '/' | '/fonts' | '/layout' | '/sidebar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FontsRoute: typeof FontsRoute
  LayoutRoute: typeof LayoutRoute
  SidebarRoute: typeof SidebarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sidebar': {
      id: '/sidebar'
      path: '/sidebar'
      fullPath: '/sidebar'
      preLoaderRoute: typeof SidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonts': {
      id: '/fonts'
      path: '/fonts'
      fullPath: '/fonts'
      preLoaderRoute: typeof FontsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FontsRoute: FontsRoute,
  LayoutRoute: LayoutRoute,
  SidebarRoute: SidebarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
