name: "Chromatic"

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            primitives:
              - 'packages/primitives/**'
            forms:
              - 'packages/forms/**'
            charts:
              - 'packages/charts/**'

  chromatic-primitives:
    needs: detect-changes
    runs-on: ubuntu-latest
    timeout-minutes: 4
    # Exclude Renovate PRs
    if: ${{ needs.detect-changes.outputs.packages != '[]' && !startsWith(github.head_ref, 'renovate/') }}

    defaults:
      run:
        working-directory: ./packages/primitives

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./packages/primitives
          buildScriptName: "storybook:build"

  chromatic-forms:
    needs: detect-changes
    runs-on: ubuntu-latest
    timeout-minutes: 4

    # Exclude Renovate PRs
    if: ${{ needs.detect-changes.outputs.packages != '[]' && !startsWith(github.head_ref, 'renovate/') }}

    defaults:
      run:
        working-directory: ./packages/forms

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_FORMS }}
          workingDir: ./packages/forms
          buildScriptName: "storybook:build"
